const COVALENT_KEY = process.env.REACT_APP_COVALENT_KEY;
 const POLYGON_TEST_NET_CHAIN_ID = 80001;
 const BINANCE_TEST_NET_CHAIN_ID = 97;
module.exports = {
  COVALENT_KEY,
  POLYGON_TEST_NET_CHAIN_ID,
  BINANCE_TEST_NET_CHAIN_ID,
  SYMBOLS: {
    97: "BNB",
    80001: "MATIC",
  },
};
